export const bankList = [
	{ bankCode: "110005", bankName: "3LINE CARD MANAGEMENT LIMITED" },
	{ bankCode: "120001", bankName: "9 PAYMENT SOLUTIONS BANK" },
	{ bankCode: "090270", bankName: "AB MICROFINANCE BANK" },
	{ bankCode: "070010", bankName: "ABBEY MORTGAGE BANK" },
	{ bankCode: "090260", bankName: "ABOVE ONLY MICROFINANCE BANK" },
	{ bankCode: "090197", bankName: "ABU MICROFINANCE BANK" },
	{ bankCode: "090545 ", bankName: "ABULESORO MICROFINANCE BANK" },
	{ bankCode: "090202", bankName: "ACCELEREX NETWORK LIMITED" },
	{ bankCode: "000014", bankName: "ACCESS BANK" },
	{ bankCode: "100013", bankName: "ACCESS MONEY" },
	{ bankCode: "100052", bankName: "ACCESS YELLO & BETA" },
	{ bankCode: "000005", bankName: "ACCESS(DIAMOND) BANK" },
	{ bankCode: "090134", bankName: "ACCION MICROFINANCE BANK" },
	{ bankCode: "090160", bankName: "ADDOSSER MICROFINANCE BANK" },
	{ bankCode: "090268", bankName: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK" },
	{ bankCode: "090155", bankName: "ADVANS LA FAYETTE  MICROFINANCE BANK" },
	{ bankCode: "090292", bankName: "AFEKHAFE MICROFINANCE BANK" },
	{ bankCode: "100028", bankName: "AG MORTGAGE BANK" },
	{ bankCode: "090371", bankName: "AGOSASA MICROFINANCE BANK" },
	{ bankCode: "090133", bankName: "AL-BARAKAH MICROFINANCE BANK" },
	{ bankCode: "090259", bankName: "ALEKUN MICROFINANCE BANK" },
	{ bankCode: "090297", bankName: "ALERT MICROFINANCE BANK" },
	{ bankCode: "090277", bankName: "AL-HAYAT MICROFINANCE BANK" },
	{ bankCode: "090131", bankName: "ALLWORKERS MICROFINANCE BANK" },
	{ bankCode: "090548", bankName: "ALLY MICROFINANCE BANK" },
	{ bankCode: "090169", bankName: "ALPHA KAPITAL MICROFINANCE BANK" },
	{ bankCode: "090394", bankName: "AMAC MICROFINANCE BANK" },
	{ bankCode: "090180", bankName: "AMJU UNIQUE MICROFINANCE BANK" },
	{ bankCode: "090116", bankName: "AMML MICROFINANCE BANK" },
	{ bankCode: "090529", bankName: "AMPERSAND MICROFINANCE BANK" },
	{ bankCode: "090143", bankName: "APEKS MICROFINANCE BANK" },
	{ bankCode: "090376", bankName: "APPLE MICROFINANCE BANK" },
	{ bankCode: "090282", bankName: "ARISE MICROFINANCE BANK" },
	{ bankCode: "090001", bankName: "ASO SAVINGS" },
	{ bankCode: "090544", bankName: "ASPIRE MICROFINANCE BANK" },
	{ bankCode: "090287", bankName: "ASSET MATRIX MICROFINANCE BANK" },
	{ bankCode: "090172", bankName: "ASTRAPOLARIS MICROFINANCE BANK" },
	{ bankCode: "090264", bankName: "AUCHI MICROFINANCE BANK" },
	{ bankCode: "090188", bankName: "BAINES CREDIT MICROFINANCE BANK" },
	{ bankCode: "090563", bankName: "BALERA MICROFINANCE BANK" },
	{ bankCode: "090326", bankName: "BALOGUN GAMBARI MICROFINANCE BANK" },
	{ bankCode: "090316", bankName: "BAYERO UNIVERSITY MICROFINANCE BANK" },
	{ bankCode: "090127", bankName: "BC KASH MICROFINANCE BANK" },
	{ bankCode: "090336", bankName: "BIPC MICROFINANCE BANK" },
	{ bankCode: "090555", bankName: "BISHOPGATE MICROFINANCE BANK" },
	{ bankCode: "090117", bankName: "BOCTRUST MICROFINANCE BANK LIMITED" },
	{ bankCode: "090395", bankName: "BORGU  MICROFINANCE BANK" },
	{ bankCode: "090176", bankName: "BOSAK MICROFINANCE BANK" },
	{ bankCode: "090148", bankName: "BOWEN MICROFINANCE BANK" },
	{ bankCode: "070015", bankName: "BRENT MORTGAGE BANK" },
	{ bankCode: "090293", bankName: "BRETHREN MICROFINANCE BANK" },
	{ bankCode: "090393", bankName: "BRIDGEWAY MICROFINANACE BANK" },
	{ bankCode: "090308", bankName: "BRIGHTWAY MICROFINANCE BANK" },
	{ bankCode: "090568", bankName: "BROADVIEW MICROFINANCE BANK" },
	{ bankCode: "090406", bankName: "BUSINESS SUPPORT MICROFINANCE BANK" },
	{ bankCode: "100026", bankName: "CARBON" },
	{ bankCode: "090360", bankName: "CASHCONNECT MICROFINANCE BANK" },
	{ bankCode: "90498", bankName: "CATLAND MICROFINANCE BANK" },
	{ bankCode: "000028", bankName: "CBN" },
	{ bankCode: "090562", bankName: "CEDAR MICROFINANCE BANK" },
	{ bankCode: "100005", bankName: "CELLULANT" },
	{ bankCode: "090154", bankName: "CEMCS MICROFINANCE BANK" },
	{ bankCode: "090141", bankName: "CHIKUM MICROFINANCE BANK" },
	{ bankCode: "090144", bankName: "CIT MICROFINANCE BANK" },
	{ bankCode: "000009", bankName: "CITI BANK" },
	{ bankCode: "090374", bankName: "COASTLINE MICROFINANCE BANK" },
	{ bankCode: "090530", bankName: "CONFIDENCE MICROFINANCE BANK" },
	{ bankCode: "090553", bankName: "CONSISTENT TRUST MICROFINANCE BANK" },
	{ bankCode: "090130", bankName: "CONSUMER MICROFINANCE BANK" },
	{ bankCode: "070021", bankName: "COOP MORTGAGE BANK" },
	{ bankCode: "090365", bankName: "CORESTEP MICROFINANCE BANK" },
	{ bankCode: "060001", bankName: "CORONATION MERCHANT BANK" },
	{ bankCode: "050001", bankName: "COUNTY FINANCE LIMITED" },
	{ bankCode: "070006", bankName: "COVENANT MICROFINANCE BANK" },
	{ bankCode: "090159", bankName: "CREDIT AFRIQUE MICROFINANCE BANK" },
	{ bankCode: "90526", bankName: "CRESCENT MICROFINANCE BANK" },
	{ bankCode: "110014", bankName: "CYBERSPACE LIMITED" },
	{ bankCode: "090391", bankName: "DAVODANI  MICROFINANCE BANK" },
	{ bankCode: "090167", bankName: "DAYLIGHT MICROFINANCE BANK" },
	{ bankCode: "090470", bankName: "DOT MICROFINANCE BANK" },
	{ bankCode: "090294", bankName: "EAGLE FLIGHT MICROFINANCE BANK" },
	{ bankCode: "100021", bankName: "EARTHOLEUM" },
	{ bankCode: "090156", bankName: "E-BARCS MICROFINANCE BANK" },
	{ bankCode: "000010", bankName: "ECOBANK" },
	{ bankCode: "100008", bankName: "ECOBANK XPRESS ACCOUNT" },
	{ bankCode: "100030", bankName: "ECOMOBILE" },
	{ bankCode: "090310", bankName: "EDFIN MICROFINANCE BANK" },
	{ bankCode: "090097", bankName: "EKONDO MICROFINANCE BANK" },
	{ bankCode: "090389", bankName: "EK-RELIABLE MICROFINANCE BANK" },
	{ bankCode: "090273", bankName: "EMERALD MICROFINANCE BANK" },
	{ bankCode: "090114", bankName: "EMPIRE TRUST MICROFINANCE BANK" },
	{ bankCode: "000019", bankName: "ENTERPRISE BANK" },
	{ bankCode: "090189", bankName: "ESAN MICROFINANCE BANK" },
	{ bankCode: "090166", bankName: "ESO-E MICROFINANCE BANK" },
	{ bankCode: "100006", bankName: "eTRANZACT" },
	{ bankCode: "090304", bankName: "EVANGEL MICROFINANCE BANK" },
	{ bankCode: "090332", bankName: "EVERGREEN MICROFINANCE BANK" },
	{ bankCode: "090541 ", bankName: "EXCELLENT MICROFINANCE BANK" },
	{ bankCode: "090328", bankName: "EYOWO" },
	{ bankCode: "090551", bankName: "FairMoney" },
	{ bankCode: "090179", bankName: "FAST MICROFINANCE BANK" },
	{ bankCode: "060002", bankName: "FBNQUEST MERCHANT BANK" },
	{ bankCode: "100031", bankName: "FCMB MOBILE" },
	{ bankCode: "090290", bankName: "FCT MICROFINANCE BANK" },
	{
		bankCode: "090398",
		bankName: "FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK",
	},
	{
		bankCode: "090318",
		bankName: "FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK",
	},
	{ bankCode: "090482", bankName: "FEDETH MICROFINANCE BANK" },
	{ bankCode: "090298", bankName: "FEDPOLY NASARAWA MICROFINANCE BANK" },
	{ bankCode: "100001", bankName: "FETS" },
	{ bankCode: "050002", bankName: "FEWCHORE FINANCE COMPANY LIMITED" },
	{ bankCode: "090153", bankName: "FFS MICROFINANCE BANK" },
	{ bankCode: "000007", bankName: "FIDELITY BANK" },
	{ bankCode: "100019", bankName: "FIDELITY MOBILE" },
	{ bankCode: "090126", bankName: "FIDFUND MICROFINANCE Bank" },
	{ bankCode: "090111", bankName: "FINATRUST MICROFINANCE BANK" },
	{ bankCode: "090400", bankName: "FINCA MICROFINANCE BANK" },
	{ bankCode: "090366", bankName: "FIRMUS MICROFINANCE BANK" },
	{ bankCode: "110004", bankName: "FIRST APPLE LIMITED" },
	{ bankCode: "000016", bankName: "FIRST BANK OF NIGERIA" },
	{ bankCode: "000003", bankName: "FIRST CITY MONUMENT BANK" },
	{ bankCode: "070014", bankName: "FIRST GENERATION MORTGAGE BANK" },
	{ bankCode: "090285", bankName: "FIRST OPTION MICROFINANCE BANK" },
	{ bankCode: "090164", bankName: "FIRST ROYAL MICROFINANCE BANK" },
	{ bankCode: "090107", bankName: "FIRST TRUST MORTGAGE BANK PLC" },
	{ bankCode: "100014", bankName: "FIRSTMONIE WALLET" },
	{
		bankCode: "110002",
		bankName: "FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED",
	},
	{ bankCode: "90521", bankName: "FORESIGHT MICROFINANCE BANK" },
	{ bankCode: "070002", bankName: "FORTIS MICROFINANCE BANK" },
	{ bankCode: "100016", bankName: "FORTIS MOBILE" },
	{ bankCode: "400001", bankName: "FSDH" },
	{ bankCode: "090145", bankName: "FULLRANGE MICROFINANCE BANK" },
	{ bankCode: "090158", bankName: "FUTO MICROFINANCE BANK" },
	{ bankCode: "090168", bankName: "GASHUA MICROFINANCE BANK" },
	{ bankCode: "070009", bankName: "GATEWAY MORTGAGE BANK" },
	{ bankCode: "090186", bankName: "GIREI MICROFINANACE BANK" },
	{ bankCode: "000027", bankName: "GLOBUS BANK" },
	{ bankCode: "090278", bankName: "GLORY MICROFINANCE BANK" },
	{ bankCode: "090408", bankName: "GMB MICROFINANCE BANK" },
	{ bankCode: "090495", bankName: "GOODNEWS MICROFINANCE BANK" },
	{ bankCode: "090122", bankName: "GOWANS MICROFINANCE BANK" },
	{ bankCode: "090550", bankName: "GREEN ENERGY MICROFINANCE BANK" },
	{ bankCode: "090178", bankName: "GREENBANK MICROFINANCE BANK" },
	{ bankCode: "090269", bankName: "GREENVILLE MICROFINANCE BANK" },
	{ bankCode: "060004", bankName: "GREENWICH MERCHANT BANK" },
	{ bankCode: "090195", bankName: "GROOMING MICROFINANCE BANK" },
	{ bankCode: "100009", bankName: "GT MOBILE" },
	{ bankCode: "000013", bankName: "GTBANK PLC" },
	{ bankCode: "090385", bankName: "GTI MICROFINANCE BANK" },
	{ bankCode: "090147", bankName: "HACKMAN MICROFINANCE BANK" },
	{ bankCode: "070017", bankName: "HAGGAI MORTGAGE BANK LIMITED" },
	{ bankCode: "090291", bankName: "HALALCREDIT MICROFINANCE BANK" },
	{ bankCode: "090121", bankName: "HASAL MICROFINANCE BANK" },
	{ bankCode: "090363", bankName: "HEADWAY MICROFINANCE BANK" },
	{ bankCode: "100017", bankName: "HEDONMARK" },
	{ bankCode: "000020", bankName: "HERITAGE BANK" },
	{ bankCode: "0070024", bankName: "HOMEBASE MORTGAGE BANK" },
	{ bankCode: "120002", bankName: "HOPEPSB" },
	{ bankCode: "090118", bankName: "IBILE MICROFINANCE BANK" },
	{ bankCode: "90519", bankName: "IBOM FADAMA MICROFINANCE BANK " },
	{ bankCode: "90520", bankName: "IC GLOBAL MICROFINANCE BANK" },
	{ bankCode: "090546", bankName: "IJEBU-IFE MICROFINANCE BANK" },
	{ bankCode: "090324", bankName: "IKENNE MICROFINANCE BANK" },
	{ bankCode: "090279", bankName: "IKIRE MICROFINANCE BANK" },
	{ bankCode: "090571", bankName: "ILARO POLY MICROFINANCE BANK" },
	{ bankCode: "090370", bankName: "ILISAN MICROFINANCE BANK" },
	{ bankCode: "090258", bankName: "IMO STATE MICROFINANCE BANK" },
	{ bankCode: "100024", bankName: "IMPERIAL HOMES MORTGAGE BANK" },
	{ bankCode: "090157", bankName: "INFINITY MICROFINANCE BANK" },
	{ bankCode: "070016", bankName: "INFINITY TRUST MORTGAGE BANK" },
	{ bankCode: "100029", bankName: "INNOVECTIVES KESH" },
	{ bankCode: "100027", bankName: "INTELLIFIN" },
	{ bankCode: "090386", bankName: "INTERLAND MICROFINANCE BANK" },
	{ bankCode: "110003", bankName: "INTERSWITCH LIMITED" },
	{ bankCode: "090149", bankName: "IRL MICROFINANCE BANK" },
	{ bankCode: "090377", bankName: "ISALEOYO MICROFINANCE BANK" },
	{ bankCode: "090543", bankName: "IWOAMA MICROFINANCE BANK" },
	{ bankCode: "090337", bankName: "IYE OKIN MICROFINANCE BANK LTD" },
	{ bankCode: "000006", bankName: "JAIZ BANK" },
	{ bankCode: "090003", bankName: "JUBILEE LIFE" },
	{ bankCode: "090320", bankName: "KADPOLY MICROFINANCE BANK" },
	{ bankCode: "090554", bankName: "KAYVEE MICROFINANCE BANK" },
	{ bankCode: "090549", bankName: "KC MICROFINANCE BANK" },
	{ bankCode: "090191", bankName: "KCMB MICROFINANCE BANK" },
	{ bankCode: "100036", bankName: "KEGOW(CHAMSMOBILE)" },
	{ bankCode: "000002", bankName: "KEYSTONE BANK" },
	{ bankCode: "100025", bankName: "KONGAPAY" },
	{ bankCode: "090299", bankName: "KONTAGORA MICROFINANCE BANK" },
	{ bankCode: "090380", bankName: "KREDI MONEY MICROFINANCE BANK" },
	{ bankCode: "090267", bankName: "KUDA MICROFINANCE BANK" },
	{ bankCode: "070012", bankName: "LAGOS BUILDING AND INVESTMENT COMPANY" },
	{ bankCode: "090177", bankName: "LAPO MICROFINANCE BANK" },
	{ bankCode: "090271", bankName: "LAVENDER MICROFINANCE BANK" },
	{ bankCode: "090372", bankName: "LEGEND MICROFINANCE BANK" },
	{ bankCode: "090557", bankName: "LIFEGATE MICROFINANCE BANK" },
	{ bankCode: "090435", bankName: "LINKS MICROFINANCE BANK" },
	{ bankCode: "070007", bankName: "LIVINGTRUST MORTGAGE BANK PLC" },
	{ bankCode: "000029", bankName: "LOTUS BANK" },
	{ bankCode: "090265", bankName: "LOVONUS MICROFINANCE BANK" },
	{ bankCode: "100035", bankName: "M36" },
	{ bankCode: "090323", bankName: "MAINLAND MICROFINANCE BANK" },
	{ bankCode: "090171", bankName: "MAINSTREET MICROFINANCE BANK" },
	{ bankCode: "090174", bankName: "MALACHY MICROFINANCE BANK" },
	{ bankCode: "090383", bankName: "MANNY MICROFINANCE BANK" },
	{ bankCode: "090410", bankName: "MARITIME MICROFINANCE BANK" },
	{ bankCode: "090321", bankName: "MAYFAIR MICROFINANCE BANK" },
	{ bankCode: "070019", bankName: "MAYFRESH MORTGAGE BANK" },
	{ bankCode: "090280", bankName: "MEGAPRAISE MICROFINANCE BANK" },
	{ bankCode: "090275", bankName: "MERIDAN MFB" },
	{ bankCode: "090136", bankName: "MICROCRED MICROFINANCE BANK" },
	{ bankCode: "090113", bankName: "MICROVIS MICROFINANCE BANK" },
	{ bankCode: "090192", bankName: "MIDLAND MICROFINANCE BANK" },
	{ bankCode: "090281", bankName: "MINT-FINEX MFB" },
	{ bankCode: "100011", bankName: "MKUDI" },
	{ bankCode: "090362", bankName: "MOLUSI MICROFINANCE BANK" },
	{ bankCode: "120003", bankName: "MOMO PAYMENT SERVICE BANK" },
	{ bankCode: "100020", bankName: "MONEY BOX" },
	{ bankCode: "090129", bankName: "MONEY TRUST MICROFINANCE BANK" },
	{ bankCode: "120005", bankName: "Moneymaster PSB" },
	{ bankCode: "090405", bankName: "MONIEPOINT MICROFINANCE BANK" },
	{ bankCode: "090392", bankName: "MOZFIN MICROFINANCE BANK" },
	{ bankCode: "090190", bankName: "MUTUAL BENEFITS MICROFINANCE BANK" },
	{ bankCode: "090151", bankName: "MUTUAL TRUST MICROFINANCE BANK" },
	{ bankCode: "090152", bankName: "NAGARTA MICROFINANCE BANK" },
	{ bankCode: "090128", bankName: "NDIORAH MICROFINANCE BANK" },
	{ bankCode: "090329", bankName: "NEPTUNE MICROFINANCE BANK" },
	{ bankCode: "090205", bankName: "NEW DAWN MICROFINANCE BANK" },
	{ bankCode: "090378", bankName: "NEW GOLDEN PASTURES MICROFINANCE BANK" },
	{ bankCode: "090108", bankName: "NEW PRUDENTIAL BANK" },
	{ bankCode: "90505", bankName: "NIGERIA PRISONS MICROFINANCE BANK" },
	{ bankCode: "090263", bankName: "NIGERIAN NAVY MICROFINANCE BANK" },
	{ bankCode: "999999", bankName: "NIP VIRTUAL BANK" },
	{ bankCode: "090194", bankName: "NIRSAL NATIONAL MICROFINANCE BANK" },
	{ bankCode: "090283", bankName: "NNEW WOMEN MICROFINANCE BANK" },
	{ bankCode: "060003", bankName: "NOVA MERCHANT BANK" },
	{ bankCode: "100032", bankName: "NOWNOW DIGITAL SYSTEMS LIMITED" },
	{ bankCode: "070001", bankName: "NPF MICROFINANCE BANK" },
	{ bankCode: "090364", bankName: "NUTURE MICROFINANCE BANK" },
	{ bankCode: "090399", bankName: "NWANNEGADI MICROFINANCE BANK" },
	{ bankCode: "090333", bankName: "OCHE MICROFINANCE BANK" },
	{ bankCode: "090119", bankName: "OHAFIA MICROFINANCE BANK" },
	{ bankCode: "090565", bankName: "OKE-ARO OREDEGBE MFB" },
	{ bankCode: "090161", bankName: "OKPOGA MICROFINANCE BANK" },
	{ bankCode: "090566", bankName: "OKUKU MICROFINANCE BANK" },
	{
		bankCode: "090272",
		bankName: "OLABISI ONABANJO UNIVERSITY MICROFINANCE",
	},
	{ bankCode: "090404", bankName: "OLOWOLAGBA MICROFINANCE BANK" },
	{ bankCode: "090295", bankName: "OMIYE MICROFINANCE BANK" },
	{ bankCode: "100004", bankName: "OPAY" },
	{ bankCode: "090567", bankName: "OROKAM MICROFINANCE BANK" },
	{ bankCode: "090396", bankName: "OSCOTECH MICROFINANCE BANK" },
	{ bankCode: "090580", bankName: "OTECH MICROFINANCE BANK" },
	{ bankCode: "090542", bankName: "OTUO MICROFINANCE BANK" },
	{ bankCode: "100002", bankName: "PAGA" },
	{ bankCode: "070008", bankName: "PAGE MFBank" },
	{ bankCode: "100033", bankName: "PALMPAY" },
	{ bankCode: "000030", bankName: "PARALLEX BANK" },
	{ bankCode: "100003", bankName: "PARKWAY-READYCASH" },
	{ bankCode: "090317", bankName: "PATRICKGOLD MICROFINANCE BANK" },
	{ bankCode: "110001", bankName: "PAYATTITUDE ONLINE" },
	{ bankCode: "110006", bankName: "PAYSTACK PAYMENT LIMITED" },
	{ bankCode: "090402", bankName: "PEACE MICROFINANCE BANK" },
	{ bankCode: "090137", bankName: "PECANTRUST MICROFINANCE BANK" },
	{ bankCode: "090196", bankName: "PENNYWISE MICROFINANCE BANK" },
	{ bankCode: "090135", bankName: "PERSONAL TRUST MICROFINANCE BANK" },
	{ bankCode: "090165", bankName: "PETRA MICROFINANCE BANK" },
	{ bankCode: "090289", bankName: "PILLAR MICROFINANCE BANK" },
	{ bankCode: "070013", bankName: "PLATINUM MORTGAGE BANK" },
	{ bankCode: "000008", bankName: "POLARIS BANK" },
	{ bankCode: "090296", bankName: "POLYUNWANA MICROFINANCE BANK" },
	{ bankCode: "000031", bankName: "PREMIUM TRUST  BANK" },
	{ bankCode: "090274", bankName: "PRESTIGE MICROFINANCE BANK" },
	{ bankCode: "000023", bankName: "PROVIDUS BANK" },
	{ bankCode: "090303", bankName: "PURPLEMONEY MICROFINANCE BANK" },
	{ bankCode: "090261", bankName: "QUICKFUND MICROFINANCE BANK" },
	{ bankCode: "000024", bankName: "RAND MERCHANT BANK" },
	{ bankCode: "070011", bankName: "REFUGE MORTGAGE BANK" },
	{ bankCode: "090125", bankName: "REGENT MICROFINANCE BANK" },
	{ bankCode: "090173", bankName: "RELIANCE MICROFINANCE BANK" },
	{ bankCode: "090198", bankName: "RENMONEY MICROFINANCE BANK" },
	{ bankCode: "090322", bankName: "REPHIDIM MICROFINANCE BANK" },
	{ bankCode: "090132", bankName: "RICHWAY MICROFINANCE BANK" },
	{ bankCode: "090433", bankName: "RIGO MICROFINANCE BANK" },
	{ bankCode: "90515", bankName: "RIMA GROWTH PATHWAY MICROFINANCE BANK" },
	{ bankCode: "90547", bankName: "ROCKSHIELD MICROFINANCE BANK" },
	{ bankCode: "090138", bankName: "ROYAL EXCHANGE MICROFINANCE BANK" },
	{ bankCode: "090175", bankName: "RUBIES MICROFINANCE BANK" },
	{ bankCode: "090286", bankName: "SAFE HAVEN MICROFINANCE BANK" },
	{ bankCode: "090485", bankName: "SAFEGATE MICROFINANCE BANK" },
	{ bankCode: "090006", bankName: "SAFETRUST" },
	{ bankCode: "090140", bankName: "SAGAMU MICROFINANCE BANK" },
	{ bankCode: "050003", bankName: "SAGE GREY FINANCE LIMITED " },
	{ bankCode: "90513", bankName: "SEAP MICROFINANCE BANK" },
	{ bankCode: "090112", bankName: "SEED CAPITAL MICROFINANCE BANK" },
	{ bankCode: "090369", bankName: "SEEDVEST MICROFINANCE BANK" },
	{ bankCode: "090401", bankName: "SHERPERD TRUST MICROFINANCE BANK" },
	{ bankCode: "090559", bankName: "SHIELD MICROFINANCE BANK" },
	{ bankCode: "090558", bankName: "SHONGOM MICROFINANCE BANK" },
	{ bankCode: "090449", bankName: "SLS MICROFINANCE BANK" },
	{ bankCode: "120004", bankName: "SMARTCASH PAYMENT SERVICE BANK" },
	{ bankCode: "090506", bankName: "SOLID ALLIANZE MICROFINANCE BANK" },
	{ bankCode: "90524", bankName: "SOLIDROCK MICROFINANCE BANK" },
	{ bankCode: "090325", bankName: "SPARKLE" },
	{ bankCode: "090436", bankName: "SPECTRUM MICROFINANCE BANK" },
	{ bankCode: "100007", bankName: "STANBIC IBTC @Ease WALLET" },
	{ bankCode: "000012", bankName: "STANBIC IBTC BANK" },
	{ bankCode: "000021", bankName: "STANDARD CHARTERED BANK" },
	{ bankCode: "090162", bankName: "STANFORD MICROFINANCE BANK" },
	{ bankCode: "090262", bankName: "STELLAS MICROFINANCE BANK" },
	{ bankCode: "000001", bankName: "STERLING BANK" },
	{ bankCode: "100022", bankName: "STERLING MOBILE" },
	{ bankCode: "090305", bankName: "SULSPAP MICROFINANCE BANK" },
	{ bankCode: "000022", bankName: "SUNTRUST BANK" },
	{ bankCode: "090446", bankName: "SUPPORT MICROFINANCE BANK" },
	{ bankCode: "090564", bankName: "SUPREME MICROFINANCE BANK" },
	{ bankCode: "100023", bankName: "TAGPAY" },
	{ bankCode: "000026", bankName: "TAJ BANK" },
	{ bankCode: "090560", bankName: "TANADI MFB (CRUST)" },
	{ bankCode: "090426", bankName: "TANGERINE MONEY" },
	{ bankCode: "090115", bankName: "TCF MICROFINANCE BANK" },
	{ bankCode: "110007", bankName: "TEAMAPT LIMITED" },
	{ bankCode: "100010", bankName: "TEASY MOBILE" },
	{ bankCode: "090373", bankName: "THINK FINANCE MICROFINANCE BANK" },
	{ bankCode: "000025", bankName: "TITAN TRUST BANK" },
	{ bankCode: "100039", bankName: "TITAN-PAYSTACK" },
	{ bankCode: "090146", bankName: "TRIDENT MICROFINANCE BANK" },
	{ bankCode: "090525", bankName: "TRIPLEA MICROFINANCE BANK" },
	{ bankCode: "090327", bankName: "TRUST MICROFINANCE BANK" },
	{ bankCode: "090123", bankName: "TRUSTBANC J6 MICROFINANCE BANK LIMITED" },
	{ bankCode: "090005", bankName: "TRUSTBOND MORTGAGE BANK" },
	{ bankCode: "090276", bankName: "TRUSTFUND MICROFINANCE BANK" },
	{ bankCode: "090315", bankName: "U & C MICROFINANCE BANK" },
	{ bankCode: "090403", bankName: "UDA MICROFINANCE BANK" },
	{ bankCode: "90517", bankName: "UHURU MICROFINANCE BANK" },
	{ bankCode: "090331", bankName: "UNAAB MICROFINANCE BANK" },
	{ bankCode: "090266", bankName: "UNIBEN MICROFINANCE BANK" },
	{ bankCode: "090193", bankName: "UNICAL MICROFINANCE BANK" },
	{ bankCode: "000018", bankName: "UNION BANK" },
	{ bankCode: "000004", bankName: "UNITED BANK FOR AFRICA" },
	{ bankCode: "000011", bankName: "UNITY BANK" },
	{
		bankCode: "090251",
		bankName: "UNIVERSITY OF NIGERIA, NSUKKA MICROFINANCE BANK",
	},
	{ bankCode: "110009", bankName: "VENTURE GARDEN NIGERIA LIMITED" },
	{ bankCode: "090474", bankName: "VERDANT MICROFINANCE BANK" },
	{ bankCode: "090110", bankName: "VFD MFB" },
	{ bankCode: "090150", bankName: "VIRTUE MICROFINANCE BANK" },
	{ bankCode: "090139", bankName: "VISA MICROFINANCE BANK" },
	{ bankCode: "100012", bankName: "VT NETWORKS" },
	{ bankCode: "000017", bankName: "WEMA BANK" },
	{ bankCode: "090120", bankName: "WETLAND  MICROFINANCE BANK" },
	{ bankCode: "090124", bankName: "XSLNCE MICROFINANCE BANK" },
	{ bankCode: "090466", bankName: "YCT MICROFINANCE BANK" },
	{ bankCode: "090142", bankName: "YES MICROFINANCE BANK" },
	{ bankCode: "090252", bankName: "YOBE MICROFINANCE  BANK" },
	{ bankCode: "000015", bankName: "ZENITH BANK" },
	{ bankCode: "100034", bankName: "ZENITH EASY WALLET" },
	{ bankCode: "100018", bankName: "ZENITH MOBILE" },
	{ bankCode: "090504", bankName: "ZIKORA MICROFINANCE BANK" },
];
