
export const LGA =    [
     {state:"Abia", lga:"Aba North"},
     {state:"Abia", lga:"Aba South"},
     {state:"Abia", lga:"Arochukwu"},
     {state:"Abia", lga:"Bende"},
     {state:"Abia", lga:"Ikwuano"},
     {state:"Abia", lga:"Isiala-Ngwa North"},
     {state:"Abia", lga:"Isiala-Ngwa South"},
     {state:"Abia", lga:"Isuikwato"},
     {state:"Abia", lga:"Obi Nwa"},
     {state:"Abia", lga:"Ohafia"},
     {state:"Abia", lga:"Osisioma"},
     {state:"Abia", lga:"Ngwa"},
     {state:"Abia", lga:"Ugwunagbo"},
     {state:"Abia", lga:"Ukwa East"},
     {state:"Abia", lga:"Ukwa West"},
     {state:"Abia", lga:"Umuahia North"},
     {state:"Abia", lga:"Umuahia South"},
     {state:"Abia", lga:"Umu-Neochi"},
     {state:"Adamawa", lga:"Demsa"},
     {state:"Adamawa", lga:"Fufore"},
     {state:"Adamawa", lga:"Ganaye"},
     {state:"Adamawa", lga:"Gireri"},
     {state:"Adamawa", lga:"Gombi"},
     {state:"Adamawa", lga:"Guyuk"},
     {state:"Adamawa", lga:"Hong"},
     {state:"Adamawa", lga:"Jada"},
     {state:"Adamawa", lga:"Lamurde"},
     {state:"Adamawa", lga:"Madagali"},
     {state:"Adamawa", lga:"Maiha"},
     {state:"Adamawa", lga:"Mayo-Belwa"},
     {state:"Adamawa", lga:"Michika"},
     {state:"Adamawa", lga:"Mubi North"},
     {state:"Adamawa", lga:"Mubi South"},
     {state:"Adamawa", lga:"Numan"},
     {state:"Adamawa", lga:"Shelleng"},
     {state:"Adamawa", lga:"Song"},
     {state:"Adamawa", lga:"Toungo"},
     {state:"Adamawa", lga:"Yola North"},
     {state:"Adamawa", lga:"Yola South"},
     {state:"Anambra", lga:"Aguata"},
     {state:"Anambra", lga:"Anambra East"},
     {state:"Anambra", lga:"Anambra West"},
     {state:"Anambra", lga:"Anaocha"},
     {state:"Anambra", lga:"Awka North"},
     {state:"Anambra", lga:"Awka South"},
     {state:"Anambra", lga:"Ayamelum"},
     {state:"Anambra", lga:"Dunukofia"},
     {state:"Anambra", lga:"Ekwusigo"},
     {state:"Anambra", lga:"Idemili North"},
     {state:"Anambra", lga:"Idemili south"},
     {state:"Anambra", lga:"Ihiala"},
     {state:"Anambra", lga:"Njikoka"},
     {state:"Anambra", lga:"Nnewi North"},
     {state:"Anambra", lga:"Nnewi South"},
     {state:"Anambra", lga:"Ogbaru"},
     {state:"Anambra", lga:"Onitsha North"},
     {state:"Anambra", lga:"Onitsha South"},
     {state:"Anambra", lga:"Orumba North"},
     {state:"Anambra", lga:"Orumba South"},
     {state:"Anambra", lga:"Oyi"},
     {state:"Akwa Ibom", lga:"Abak"},
     {state:"Akwa Ibom", lga:"Eastern Obolo"},
     {state:"Akwa Ibom", lga:"Eket"},
     {state:"Akwa Ibom", lga:"Esit Eket"},
     {state:"Akwa Ibom", lga:"Essien Udim"},
     {state:"Akwa Ibom", lga:"Etim Ekpo"},
     {state:"Akwa Ibom", lga:"Etinan"},
     {state:"Akwa Ibom", lga:"Ibeno"},
     {state:"Akwa Ibom", lga:"Ibesikpo Asutan"},
     {state:"Akwa Ibom", lga:"Ibiono Ibom"},
     {state:"Akwa Ibom", lga:"Ika"},
     {state:"Akwa Ibom", lga:"Ikono"},
     {state:"Akwa Ibom", lga:"Ikot Abasi"},
     {state:"Akwa Ibom", lga:"Ikot Ekpene"},
     {state:"Akwa Ibom", lga:"Ini"},
     {state:"Akwa Ibom", lga:"Itu"},
     {state:"Akwa Ibom", lga:"Mbo"},
     {state:"Akwa Ibom", lga:"Mkpat Enin"},
     {state:"Akwa Ibom", lga:"Nsit Atai"},
     {state:"Akwa Ibom", lga:"Nsit Ibom"},
     {state:"Akwa Ibom", lga:"Nsit Ubium"},
     {state:"Akwa Ibom", lga:"Obot Akara"},
     {state:"Akwa Ibom", lga:"Okobo"},
     {state:"Akwa Ibom", lga:"Onna"},
     {state:"Akwa Ibom", lga:"Oron"},
     {state:"Akwa Ibom", lga:"Oruk Anam"},
     {state:"Akwa Ibom", lga:"Udung Uko"},
     {state:"Akwa Ibom", lga:"Ukanafun"},
     {state:"Akwa Ibom", lga:"Uruan"},
     {state:"Akwa Ibom", lga:"Urue-Offong/Oruko "},
     {state:"Akwa Ibom", lga:"Uyo"},
     {state:"Bauchi", lga:"Alkaleri"},
     {state:"Bauchi", lga:"Bauchi"},
     {state:"Bauchi", lga:"Bogoro"},
     {state:"Bauchi", lga:"Damban"},
     {state:"Bauchi", lga:"Darazo"},
     {state:"Bauchi", lga:"Dass"},
     {state:"Bauchi", lga:"Ganjuwa"},
     {state:"Bauchi", lga:"Giade"},
     {state:"Bauchi", lga:"Itas/Gadau"},
     {state:"Bauchi", lga:"Jama'are"},
     {state:"Bauchi", lga:"Katagum"},
     {state:"Bauchi", lga:"Kirfi"},
     {state:"Bauchi", lga:"Misau"},
     {state:"Bauchi", lga:"Ningi"},
     {state:"Bauchi", lga:"Shira"},
     {state:"Bauchi", lga:"Tafawa-Balewa"},
     {state:"Bauchi", lga:"Toro"},
     {state:"Bauchi", lga:"Warji"},
     {state:"Bauchi", lga:"Zaki"},
     {state:"Bayelsa", lga:"Brass"},
     {state:"Bayelsa", lga:"Ekeremor"},
     {state:"Bayelsa", lga:"Kolokuma/Opokuma"},
     {state:"Bayelsa", lga:"Nembe"},
     {state:"Bayelsa", lga:"Ogbia"},
     {state:"Bayelsa", lga:"Sagbama"},
     {state:"Bayelsa", lga:"Southern Jaw"},
     {state:"Bayelsa", lga:"Yenegoa"},
     {state:"Benue", lga:"Ado"},
     {state:"Benue", lga:"Agatu"},
     {state:"Benue", lga:"Apa"},
     {state:"Benue", lga:"Buruku"},
     {state:"Benue", lga:"Gboko"},
     {state:"Benue", lga:"Guma"},
     {state:"Benue", lga:"Gwer East"},
     {state:"Benue", lga:"Gwer West"},
     {state:"Benue", lga:"Katsina-Ala"},
     {state:"Benue", lga:"Konshisha"},
     {state:"Benue", lga:"Kwande"},
     {state:"Benue", lga:"Logo"},
     {state:"Benue", lga:"Makurdi"},
     {state:"Benue", lga:"Obi"},
     {state:"Benue", lga:"Ogbadibo"},
     {state:"Benue", lga:"Oju"},
     {state:"Benue", lga:"Okpokwu"},
     {state:"Benue", lga:"Ohimini"},
     {state:"Benue", lga:"Oturkpo"},
     {state:"Benue", lga:"Tarka"},
     {state:"Benue", lga:"Ukum"},
     {state:"Benue", lga:"Ushongo"},
     {state:"Benue", lga:"Vandeikya"},
     {state:"Borno", lga:"Abadam"},
     {state:"Borno", lga:"Askira/Uba"},
     {state:"Borno", lga:"Bama"},
     {state:"Borno", lga:"Bayo"},
     {state:"Borno", lga:"Biu"},
     {state:"Borno", lga:"Chibok"},
     {state:"Borno", lga:"Damboa"},
     {state:"Borno", lga:"Dikwa"},
     {state:"Borno", lga:"Gubio"},
     {state:"Borno", lga:"Guzamala"},
     {state:"Borno", lga:"Gwoza"},
     {state:"Borno", lga:"Hawul"},
     {state:"Borno", lga:"Jere"},
     {state:"Borno", lga:"Kaga"},
     {state:"Borno", lga:"Kala/Balge"},
     {state:"Borno", lga:"Konduga"},
     {state:"Borno", lga:"Kukawa"},
     {state:"Borno", lga:"Kwaya Kusar"},
     {state:"Borno", lga:"Mafa"},
     {state:"Borno", lga:"Magumeri"},
     {state:"Borno", lga:"Maiduguri"},
     {state:"Borno", lga:"Marte"},
     {state:"Borno", lga:"Mobbar"},
     {state:"Borno", lga:"Monguno"},
     {state:"Borno", lga:"Ngala"},
     {state:"Borno", lga:"Nganzai"},
     {state:"Borno", lga:"Shani"},
     {state:"Cross River", lga:"Akpabuyo"},
     {state:"Cross River", lga:"Odukpani"},
     {state:"Cross River", lga:"Akamkpa"},
     {state:"Cross River", lga:"Biase"},
     {state:"Cross River", lga:"Abi"},
     {state:"Cross River", lga:"Ikom"},
     {state:"Cross River", lga:"Yarkur"},
     {state:"Cross River", lga:"Odubra"},
     {state:"Cross River", lga:"Boki"},
     {state:"Cross River", lga:"Ogoja"},
     {state:"Cross River", lga:"Yala"},
     {state:"Cross River", lga:"Obanliku"},
     {state:"Cross River", lga:"Obudu"},
     {state:"Cross River", lga:"Calabar South"},
     {state:"Cross River", lga:"Etung"},
     {state:"Cross River", lga:"Bekwara"},
     {state:"Cross River", lga:"Bakassi"},
     {state:"Cross River", lga:"Calabar Municipality"},
     {state:"Delta", lga:"Oshimili"},
     {state:"Delta", lga:"Aniocha"},
     {state:"Delta", lga:"Aniocha South"},
     {state:"Delta", lga:"Ika South"},
     {state:"Delta", lga:"Ika North-East"},
     {state:"Delta", lga:"Ndokwa West"},
     {state:"Delta", lga:"Ndokwa East"},
     {state:"Delta", lga:"Isoko south"},
     {state:"Delta", lga:"Isoko North"},
     {state:"Delta", lga:"Bomadi"},
     {state:"Delta", lga:"Burutu"},
     {state:"Delta", lga:"Ughelli South"},
     {state:"Delta", lga:"Ughelli North"},
     {state:"Delta", lga:"Ethiope West"},
     {state:"Delta", lga:"Ethiope East"},
     {state:"Delta", lga:"Sapele"},
     {state:"Delta", lga:"Okpe"},
     {state:"Delta", lga:"Warri North"},
     {state:"Delta", lga:"Warri South"},
     {state:"Delta", lga:"Uvwie"},
     {state:"Delta", lga:"Udu"},
     {state:"Delta", lga:"Warri Central"},
     {state:"Delta", lga:"Ukwani"},
     {state:"Delta", lga:"Oshimili North"},
     {state:"Delta", lga:"Patani"},
     {state:"Ebonyi", lga:"Afikpo South"},
     {state:"Ebonyi", lga:"Afikpo North"},
     {state:"Ebonyi", lga:"Onicha"},
     {state:"Ebonyi", lga:"Ohaozara"},
     {state:"Ebonyi", lga:"Abakaliki"},
     {state:"Ebonyi", lga:"Ishielu"},
     {state:"Ebonyi", lga:"lkwo"},
     {state:"Ebonyi", lga:"Ezza"},
     {state:"Ebonyi", lga:"Ezza South"},
     {state:"Ebonyi", lga:"Ohaukwu"},
     {state:"Ebonyi", lga:"Ebonyi"},
     {state:"Ebonyi", lga:"Ivo"},
     {state:"Enugu", lga:"Enugu South,"},
     {state:"Enugu", lga:"Igbo-Eze South"},
     {state:"Enugu", lga:"Enugu North"},
     {state:"Enugu", lga:"Nkanu"},
     {state:"Enugu", lga:"Udi Agwu"},
     {state:"Enugu", lga:"Oji-River"},
     {state:"Enugu", lga:"Ezeagu"},
     {state:"Enugu", lga:"IgboEze North"},
     {state:"Enugu", lga:"Isi-Uzo"},
     {state:"Enugu", lga:"Nsukka"},
     {state:"Enugu", lga:"Igbo-Ekiti"},
     {state:"Enugu", lga:"Uzo-Uwani"},
     {state:"Enugu", lga:"Enugu Eas"},
     {state:"Enugu", lga:"Aninri"},
     {state:"Enugu", lga:"Nkanu East"},
     {state:"Enugu", lga:"Udenu."},
     {state:"Edo", lga:"Esan North-East"},
     {state:"Edo", lga:"Esan Central"},
     {state:"Edo", lga:"Esan West"},
     {state:"Edo", lga:"Egor"},
     {state:"Edo", lga:"Ukpoba"},
     {state:"Edo", lga:"Central"},
     {state:"Edo", lga:"Etsako Central"},
     {state:"Edo", lga:"Igueben"},
     {state:"Edo", lga:"Oredo"},
     {state:"Edo", lga:"Ovia SouthWest"},
     {state:"Edo", lga:"Ovia South-East"},
     {state:"Edo", lga:"Orhionwon"},
     {state:"Edo", lga:"Uhunmwonde"},
     {state:"Edo", lga:"Etsako East"},
     {state:"Edo", lga:"Esan South-East"},
     {state:"Ekiti", lga:"Ado"},
     {state:"Ekiti", lga:"Ekiti-East"},
     {state:"Ekiti", lga:"Ekiti-West"},
     {state:"Ekiti", lga:"Emure/Ise/Orun"},
     {state:"Ekiti", lga:"Ekiti South-West"},
     {state:"Ekiti", lga:"Ikere Ekiti"},
     {state:"Ekiti", lga:"Irepodun"},
     {state:"Ekiti", lga:"Ijero,"},
     {state:"Ekiti", lga:"Ido/Osi"},
     {state:"Ekiti", lga:"Oye"},
     {state:"Ekiti", lga:"Ikole"},
     {state:"Ekiti", lga:"Moba"},
     {state:"Ekiti", lga:"Gbonyin"},
     {state:"Ekiti", lga:"Efon"},
     {state:"Ekiti", lga:"Ise/Orun"},
     {state:"Ekiti", lga:"Ilejemeje."},
     {state:"FCT - Abuja", lga:"Abaji"},
     {state:"FCT - Abuja", lga:"Abuja Municipal"},
     {state:"FCT - Abuja", lga:"Bwari"},
     {state:"FCT - Abuja", lga:"Gwagwalada"},
     {state:"FCT - Abuja", lga:"Kuje"},
     {state:"FCT - Abuja", lga:"Kwali"},
     {state:"Gombe", lga:"Akko"},
     {state:"Gombe", lga:"Balanga"},
     {state:"Gombe", lga:"Billiri"},
     {state:"Gombe", lga:"Dukku"},
     {state:"Gombe", lga:"Kaltungo"},
     {state:"Gombe", lga:"Kwami"},
     {state:"Gombe", lga:"Shomgom"},
     {state:"Gombe", lga:"Funakaye"},
     {state:"Gombe", lga:"Gombe"},
     {state:"Gombe", lga:"Nafada/Bajoga"},
     {state:"Gombe", lga:"Yamaltu/Delta."},
     {state:"Imo", lga:"Aboh-Mbaise"},
     {state:"Imo", lga:"Ahiazu-Mbaise"},
     {state:"Imo", lga:"Ehime-Mbano"},
     {state:"Imo", lga:"Ezinihitte"},
     {state:"Imo", lga:"Ideato North"},
     {state:"Imo", lga:"Ideato South"},
     {state:"Imo", lga:"Ihitte/Uboma"},
     {state:"Imo", lga:"Ikeduru"},
     {state:"Imo", lga:"Isiala Mbano"},
     {state:"Imo", lga:"Isu"},
     {state:"Imo", lga:"Mbaitoli"},
     {state:"Imo", lga:"Mbaitoli"},
     {state:"Imo", lga:"Ngor-Okpala"},
     {state:"Imo", lga:"Njaba"},
     {state:"Imo", lga:"Nwangele"},
     {state:"Imo", lga:"Nkwerre"},
     {state:"Imo", lga:"Obowo"},
     {state:"Imo", lga:"Oguta"},
     {state:"Imo", lga:"Ohaji/Egbema"},
     {state:"Imo", lga:"Okigwe"},
     {state:"Imo", lga:"Orlu"},
     {state:"Imo", lga:"Orsu"},
     {state:"Imo", lga:"Oru East"},
     {state:"Imo", lga:"Oru West"},
     {state:"Imo", lga:"Owerri-Municipal"},
     {state:"Imo", lga:"Owerri North"},
     {state:"Imo", lga:"Owerri West"},
     {state:"Jigawa", lga:"Auyo"},
     {state:"Jigawa", lga:"Babura"},
     {state:"Jigawa", lga:"Birni Kudu"},
     {state:"Jigawa", lga:"Biriniwa"},
     {state:"Jigawa", lga:"Buji"},
     {state:"Jigawa", lga:"Dutse"},
     {state:"Jigawa", lga:"Gagarawa"},
     {state:"Jigawa", lga:"Garki"},
     {state:"Jigawa", lga:"Gumel"},
     {state:"Jigawa", lga:"Guri"},
     {state:"Jigawa", lga:"Gwaram"},
     {state:"Jigawa", lga:"Gwiwa"},
     {state:"Jigawa", lga:"Hadejia"},
     {state:"Jigawa", lga:"Jahun"},
     {state:"Jigawa", lga:"Kafin Hausa"},
     {state:"Jigawa", lga:"Kaugama Kazaure"},
     {state:"Jigawa", lga:"Kiri Kasamma"},
     {state:"Jigawa", lga:"Kiyawa"},
     {state:"Jigawa", lga:"Maigatari"},
     {state:"Jigawa", lga:"Malam Madori"},
     {state:"Jigawa", lga:"Miga"},
     {state:"Jigawa", lga:"Ringim"},
     {state:"Jigawa", lga:"Roni"},
     {state:"Jigawa", lga:"Sule-Tankarkar"},
     {state:"Jigawa", lga:"Taura"},
     {state:"Jigawa", lga:"Yankwashi"},
     {state:"Kaduna", lga:"Birni-Gwari"},
     {state:"Kaduna", lga:"Chikun"},
     {state:"Kaduna", lga:"Giwa"},
     {state:"Kaduna", lga:"Igabi"},
     {state:"Kaduna", lga:"Ikara"},
     {state:"Kaduna", lga:"jaba"},
     {state:"Kaduna", lga:"Jema'a"},
     {state:"Kaduna", lga:"Kachia"},
     {state:"Kaduna", lga:"Kaduna North"},
     {state:"Kaduna", lga:"Kaduna South"},
     {state:"Kaduna", lga:"Kagarko"},
     {state:"Kaduna", lga:"Kajuru"},
     {state:"Kaduna", lga:"Kaura"},
     {state:"Kaduna", lga:"Kauru"},
     {state:"Kaduna", lga:"Kubau"},
     {state:"Kaduna", lga:"Kudan"},
     {state:"Kaduna", lga:"Lere"},
     {state:"Kaduna", lga:"Makarfi"},
     {state:"Kaduna", lga:"Sabon-Gari"},
     {state:"Kaduna", lga:"Sanga"},
     {state:"Kaduna", lga:"Soba"},
     {state:"Kaduna", lga:"Zango-Kataf"},
     {state:"Kaduna", lga:"Zaria"},
     {state:"Kano", lga:"Ajingi"},
     {state:"Kano", lga:"Albasu"},
     {state:"Kano", lga:"Bagwai"},
     {state:"Kano", lga:"Bebeji"},
     {state:"Kano", lga:"Bichi"},
     {state:"Kano", lga:"Bunkure"},
     {state:"Kano", lga:"Dala"},
     {state:"Kano", lga:"Dambatta"},
     {state:"Kano", lga:"Dawakin Kudu"},
     {state:"Kano", lga:"Dawakin Tofa"},
     {state:"Kano", lga:"Doguwa"},
     {state:"Kano", lga:"Fagge"},
     {state:"Kano", lga:"Gabasawa"},
     {state:"Kano", lga:"Garko"},
     {state:"Kano", lga:"Garum"},
     {state:"Kano", lga:"Mallam"},
     {state:"Kano", lga:"Gaya"},
     {state:"Kano", lga:"Gezawa"},
     {state:"Kano", lga:"Gwale"},
     {state:"Kano", lga:"Gwarzo"},
     {state:"Kano", lga:"Kabo"},
     {state:"Kano", lga:"Kano Municipal"},
     {state:"Kano", lga:"Karaye"},
     {state:"Kano", lga:"Kibiya"},
     {state:"Kano", lga:"Kiru"},
     {state:"Kano", lga:"kumbotso"},
     {state:"Kano", lga:"Kunchi"},
     {state:"Kano", lga:"Kura"},
     {state:"Kano", lga:"Madobi"},
     {state:"Kano", lga:"Makoda"},
     {state:"Kano", lga:"Minjibir"},
     {state:"Kano", lga:"Nasarawa"},
     {state:"Kano", lga:"Rano"},
     {state:"Kano", lga:"Rimin Gado"},
     {state:"Kano", lga:"Rogo"},
     {state:"Kano", lga:"Shanono"},
     {state:"Kano", lga:"Sumaila"},
     {state:"Kano", lga:"Takali"},
     {state:"Kano", lga:"Tarauni"},
     {state:"Kano", lga:"Tofa"},
     {state:"Kano", lga:"Tsanyawa"},
     {state:"Kano", lga:"Tudun Wada"},
     {state:"Kano", lga:"Ungogo"},
     {state:"Kano", lga:"Warawa"},
     {state:"Kano", lga:"Wudil"},
     {state:"Katsina", lga:"Bakori"},
     {state:"Katsina", lga:"Batagarawa"},
     {state:"Katsina", lga:"Batsari"},
     {state:"Katsina", lga:"Baure"},
     {state:"Katsina", lga:"Bindawa"},
     {state:"Katsina", lga:"Charanchi"},
     {state:"Katsina", lga:"Dandume"},
     {state:"Katsina", lga:"Danja"},
     {state:"Katsina", lga:"Dan Musa"},
     {state:"Katsina", lga:"Daura"},
     {state:"Katsina", lga:"Dutsi"},
     {state:"Katsina", lga:"Dutsin-Ma"},
     {state:"Katsina", lga:"Faskari"},
     {state:"Katsina", lga:"Funtua"},
     {state:"Katsina", lga:"Ingawa"},
     {state:"Katsina", lga:"Jibia"},
     {state:"Katsina", lga:"Kafur"},
     {state:"Katsina", lga:"Kaita"},
     {state:"Katsina", lga:"Kankara"},
     {state:"Katsina", lga:"Kankia"},
     {state:"Katsina", lga:"Katsina"},
     {state:"Katsina", lga:"Kurfi"},
     {state:"Katsina", lga:"Kusada"},
     {state:"Katsina", lga:"Mai'Adua"},
     {state:"Katsina", lga:"Malumfashi"},
     {state:"Katsina", lga:"Mani"},
     {state:"Katsina", lga:"Mashi"},
     {state:"Katsina", lga:"Matazuu"},
     {state:"Katsina", lga:"Musawa"},
     {state:"Katsina", lga:"Rimi"},
     {state:"Katsina", lga:"Sabuwa"},
     {state:"Katsina", lga:"Safana"},
     {state:"Katsina", lga:"Sandamu"},
     {state:"Katsina", lga:"Zango"},
     {state:"Kebbi", lga:"Aleiro"},
     {state:"Kebbi", lga:"Arewa-Dandi"},
     {state:"Kebbi", lga:"Argungu"},
     {state:"Kebbi", lga:"Augie"},
     {state:"Kebbi", lga:"Bagudo"},
     {state:"Kebbi", lga:"Birnin Kebbi"},
     {state:"Kebbi", lga:"Bunza"},
     {state:"Kebbi", lga:"Dandi"},
     {state:"Kebbi", lga:"Fakai"},
     {state:"Kebbi", lga:"Gwandu"},
     {state:"Kebbi", lga:"Jega"},
     {state:"Kebbi", lga:"Kalgo"},
     {state:"Kebbi", lga:"Koko/Besse"},
     {state:"Kebbi", lga:"Maiyama"},
     {state:"Kebbi", lga:"Ngaski"},
     {state:"Kebbi", lga:"Sakaba"},
     {state:"Kebbi", lga:"Shanga"},
     {state:"Kebbi", lga:"Suru"},
     {state:"Kebbi", lga:"Wasagu/Danko"},
     {state:"Kebbi", lga:"Yauri"},
     {state:"Kebbi", lga:"Zuru"},
     {state:"Kogi", lga:"Adavi"},
     {state:"Kogi", lga:"Ajaokuta"},
     {state:"Kogi", lga:"Ankpa"},
     {state:"Kogi", lga:"Bassa"},
     {state:"Kogi", lga:"Dekina"},
     {state:"Kogi", lga:"Ibaji"},
     {state:"Kogi", lga:"Idah"},
     {state:"Kogi", lga:"Igalamela-Odolu"},
     {state:"Kogi", lga:"Ijumu"},
     {state:"Kogi", lga:"Kabba/Bunu"},
     {state:"Kogi", lga:"Kogi"},
     {state:"Kogi", lga:"Lokoja"},
     {state:"Kogi", lga:"Mopa-Muro"},
     {state:"Kogi", lga:"Ofu"},
     {state:"Kogi", lga:"Ogori/Mangongo"},
     {state:"Kogi", lga:"Okehi"},
     {state:"Kogi", lga:"Okene"},
     {state:"Kogi", lga:"Olamabolo"},
     {state:"Kogi", lga:"Omala"},
     {state:"Kogi", lga:"Yagba East"},
     {state:"Kogi", lga:"Yagba West"},
     {state:"Kwara", lga:"Asa"},
     {state:"Kwara", lga:"Baruten"},
     {state:"Kwara", lga:"Edu"},
     {state:"Kwara", lga:"Ekiti"},
     {state:"Kwara", lga:"Ifelodun"},
     {state:"Kwara", lga:"Ilorin East"},
     {state:"Kwara", lga:"Ilorin West"},
     {state:"Kwara", lga:"Irepodun"},
     {state:"Kwara", lga:"Isin"},
     {state:"Kwara", lga:"Kaiama"},
     {state:"Kwara", lga:"Moro"},
     {state:"Kwara", lga:"Offa"},
     {state:"Kwara", lga:"Oke-Ero"},
     {state:"Kwara", lga:"Oyun"},
     {state:"Kwara", lga:"Pategi"},
     {state:"Lagos", lga:"Agege"},
     {state:"Lagos", lga:"Ajeromi-Ifelodun"},
     {state:"Lagos", lga:"Alimosho"},
     {state:"Lagos", lga:"Amuwo-Odofin"},
     {state:"Lagos", lga:"Apapa"},
     {state:"Lagos", lga:"Badagry"},
     {state:"Lagos", lga:"Epe"},
     {state:"Lagos", lga:"Eti-Osa"},
     {state:"Lagos", lga:"Ibeju/Lekki"},
     {state:"Lagos", lga:"Ifako-Ijaye"},
     {state:"Lagos", lga:"Ikeja"},
     {state:"Lagos", lga:"Ikorodu"},
     {state:"Lagos", lga:"Kosofe"},
     {state:"Lagos", lga:"Lagos Island"},
     {state:"Lagos", lga:"Lagos Mainland"},
     {state:"Lagos", lga:"Mushin"},
     {state:"Lagos", lga:"Ojo"},
     {state:"Lagos", lga:"Oshodi-Isolo"},
     {state:"Lagos", lga:"Shomolu"},
     {state:"Lagos", lga:"Surulere"},
     {state:"Nasarawa", lga:"Akwanga"},
     {state:"Nasarawa", lga:"Awe"},
     {state:"Nasarawa", lga:"Doma"},
     {state:"Nasarawa", lga:"Karu"},
     {state:"Nasarawa", lga:"Keana"},
     {state:"Nasarawa", lga:"Keffi"},
     {state:"Nasarawa", lga:"Kokona"},
     {state:"Nasarawa", lga:"Lafia"},
     {state:"Nasarawa", lga:"Nasarawa"},
     {state:"Nasarawa", lga:"Nasarawa-Eggon"},
     {state:"Nasarawa", lga:"Obi"},
     {state:"Nasarawa", lga:"Toto"},
     {state:"Nasarawa", lga:"Wamba"},
     {state:"Niger", lga:"Agaie"},
     {state:"Niger", lga:"Agwara"},
     {state:"Niger", lga:"Bida"},
     {state:"Niger", lga:"Borgu"},
     {state:"Niger", lga:"Bosso"},
     {state:"Niger", lga:"Chanchaga"},
     {state:"Niger", lga:"Edati"},
     {state:"Niger", lga:"Gbako"},
     {state:"Niger", lga:"Gurara"},
     {state:"Niger", lga:"Katcha"},
     {state:"Niger", lga:"Kontagora"},
     {state:"Niger", lga:"Lapai"},
     {state:"Niger", lga:"Lavun"},
     {state:"Niger", lga:"Magama"},
     {state:"Niger", lga:"Mariga"},
     {state:"Niger", lga:"Mashegu"},
     {state:"Niger", lga:"Mokwa"},
     {state:"Niger", lga:"Muya"},
     {state:"Niger", lga:"Pailoro"},
     {state:"Niger", lga:"Rafi"},
     {state:"Niger", lga:"Rijau"},
     {state:"Niger", lga:"Shiroro"},
     {state:"Niger", lga:"Suleja"},
     {state:"Niger", lga:"Tafa"},
     {state:"Niger", lga:"Wushishi"},
     {state:"Ogun", lga:"Abeokuta North"},
     {state:"Ogun", lga:"Abeokuta South"},
     {state:"Ogun", lga:"Ado-Odo/Ota"},
     {state:"Ogun", lga:"Egbado North"},
     {state:"Ogun", lga:"Egbado South"},
     {state:"Ogun", lga:"Ewekoro"},
     {state:"Ogun", lga:"Ifo"},
     {state:"Ogun", lga:"Ijebu East"},
     {state:"Ogun", lga:"Ijebu North"},
     {state:"Ogun", lga:"Ijebu North East"},
     {state:"Ogun", lga:"Ijebu Ode"},
     {state:"Ogun", lga:"Ikenne"},
     {state:"Ogun", lga:"Imeko-Afon"},
     {state:"Ogun", lga:"Ipokia"},
     {state:"Ogun", lga:"Obafemi-Owode"},
     {state:"Ogun", lga:"Ogun Waterside"},
     {state:"Ogun", lga:"Odeda"},
     {state:"Ogun", lga:"Odogbolu"},
     {state:"Ogun", lga:"Remo North"},
     {state:"Ogun", lga:"Shagamu"},
     {state:"Ondo", lga:"Akoko North East"},
     {state:"Ondo", lga:"Akoko North West"},
     {state:"Ondo", lga:"Akoko South Akure East"},
     {state:"Ondo", lga:"Akoko South West"},
     {state:"Ondo", lga:"Akure North"},
     {state:"Ondo", lga:"Akure South"},
     {state:"Ondo", lga:"Ese-Odo"},
     {state:"Ondo", lga:"Idanre"},
     {state:"Ondo", lga:"Ifedore"},
     {state:"Ondo", lga:"Ilaje"},
     {state:"Ondo", lga:"Ile-Oluji"},
     {state:"Ondo", lga:"Okeigbo"},
     {state:"Ondo", lga:"Irele"},
     {state:"Ondo", lga:"Odigbo"},
     {state:"Ondo", lga:"Okitipupa"},
     {state:"Ondo", lga:"Ondo East"},
     {state:"Ondo", lga:"Ondo West"},
     {state:"Ondo", lga:"Ose"},
     {state:"Ondo", lga:"Owo"},
     {state:"Osun", lga:"Aiyedade"},
     {state:"Osun", lga:"Aiyedire"},
     {state:"Osun", lga:"Atakumosa East"},
     {state:"Osun", lga:"Atakumosa West"},
     {state:"Osun", lga:"Boluwaduro"},
     {state:"Osun", lga:"Boripe"},
     {state:"Osun", lga:"Ede North"},
     {state:"Osun", lga:"Ede South"},
     {state:"Osun", lga:"Egbedore"},
     {state:"Osun", lga:"Ejigbo"},
     {state:"Osun", lga:"Ife Central"},
     {state:"Osun", lga:"Ife East"},
     {state:"Osun", lga:"Ife North"},
     {state:"Osun", lga:"Ife South"},
     {state:"Osun", lga:"Ifedayo"},
     {state:"Osun", lga:"Ifelodun"},
     {state:"Osun", lga:"Ila"},
     {state:"Osun", lga:"Ilesha East"},
     {state:"Osun", lga:"Ilesha West"},
     {state:"Osun", lga:"Irepodun"},
     {state:"Osun", lga:"Irewole"},
     {state:"Osun", lga:"Isokan"},
     {state:"Osun", lga:"Iwo"},
     {state:"Osun", lga:"Obokun"},
     {state:"Osun", lga:"Odo-Otin"},
     {state:"Osun", lga:"Ola-Oluwa"},
     {state:"Osun", lga:"Olorunda"},
     {state:"Osun", lga:"Oriade"},
     {state:"Osun", lga:"Orolu"},
     {state:"Osun", lga:"Osogbo"},
     {state:"Oyo", lga:"Afijio"},
     {state:"Oyo", lga:"Akinyele"},
     {state:"Oyo", lga:"Atiba"},
     {state:"Oyo", lga:"Atigbo"},
     {state:"Oyo", lga:"Egbeda"},
     {state:"Oyo", lga:"Ibadan Central"},
     {state:"Oyo", lga:"Ibadan North"},
     {state:"Oyo", lga:"Ibadan North West"},
     {state:"Oyo", lga:"Ibadan South East"},
     {state:"Oyo", lga:"Ibadan South West"},
     {state:"Oyo", lga:"Ibarapa Central"},
     {state:"Oyo", lga:"Ibarapa East"},
     {state:"Oyo", lga:"Ibarapa North"},
     {state:"Oyo", lga:"Ido"},
     {state:"Oyo", lga:"Irepo"},
     {state:"Oyo", lga:"Iseyin"},
     {state:"Oyo", lga:"Itesiwaju"},
     {state:"Oyo", lga:"Iwajowa"},
     {state:"Oyo", lga:"Kajola"},
     {state:"Oyo", lga:"Lagelu Ogbomosho North"},
     {state:"Oyo", lga:"Ogbomosho South"},
     {state:"Oyo", lga:"Ogo Oluwa"},
     {state:"Oyo", lga:"Olorunsogo"},
     {state:"Oyo", lga:"Oluyole"},
     {state:"Oyo", lga:"Ona-Ara"},
     {state:"Oyo", lga:"Orelope"},
     {state:"Oyo", lga:"Ori Ire"},
     {state:"Oyo", lga:"Oyo East"},
     {state:"Oyo", lga:"Oyo West"},
     {state:"Oyo", lga:"Saki East"},
     {state:"Oyo", lga:"Saki West"},
     {state:"Oyo", lga:"Surulere"},
     {state:"Plateau", lga:"Barikin Ladi"},
     {state:"Plateau", lga:"Bassa"},
     {state:"Plateau", lga:"Bokkos"},
     {state:"Plateau", lga:"Jos East"},
     {state:"Plateau", lga:"Jos North"},
     {state:"Plateau", lga:"Jos South"},
     {state:"Plateau", lga:"Kanam"},
     {state:"Plateau", lga:"Kanke"},
     {state:"Plateau", lga:"Langtang North"},
     {state:"Plateau", lga:"Langtang South"},
     {state:"Plateau", lga:"Mangu"},
     {state:"Plateau", lga:"Mikang"},
     {state:"Plateau", lga:"Pankshin"},
     {state:"Plateau", lga:"Qua'an Pan"},
     {state:"Plateau", lga:"Riyom"},
     {state:"Plateau", lga:"Shendam"},
     {state:"Plateau", lga:"Wase"},
     {state:"Rivers", lga:"Abua/Odual"},
     {state:"Rivers", lga:"Ahoada East"},
     {state:"Rivers", lga:"Ahoada West"},
     {state:"Rivers", lga:"Akuku Toru"},
     {state:"Rivers", lga:"Andoni"},
     {state:"Rivers", lga:"Asari-Toru"},
     {state:"Rivers", lga:"Bonny"},
     {state:"Rivers", lga:"Degema"},
     {state:"Rivers", lga:"Emohua"},
     {state:"Rivers", lga:"Eleme"},
     {state:"Rivers", lga:"Etche"},
     {state:"Rivers", lga:"Gokana"},
     {state:"Rivers", lga:"Ikwerre"},
     {state:"Rivers", lga:"Khana"},
     {state:"Rivers", lga:"Obia/Akpor"},
     {state:"Rivers", lga:"Ogba/Egbema/Ndoni"},
     {state:"Rivers", lga:"Ogu/Bolo"},
     {state:"Rivers", lga:"Okrika"},
     {state:"Rivers", lga:"Omumma"},
     {state:"Rivers", lga:"Opobo/Nkoro"},
     {state:"Rivers", lga:"Oyigbo"},
     {state:"Rivers", lga:"Port-Harcourt"},
     {state:"Rivers", lga:"Tai"},
     {state:"Sokoto", lga:"Binji"},
     {state:"Sokoto", lga:"Bodinga"},
     {state:"Sokoto", lga:"Dange-shnsi"},
     {state:"Sokoto", lga:"Gada"},
     {state:"Sokoto", lga:"Goronyo"},
     {state:"Sokoto", lga:"Gudu"},
     {state:"Sokoto", lga:"Gawabawa"},
     {state:"Sokoto", lga:"Illela"},
     {state:"Sokoto", lga:"Isa"},
     {state:"Sokoto", lga:"Kware"},
     {state:"Sokoto", lga:"kebbe"},
     {state:"Sokoto", lga:"Rabah"},
     {state:"Sokoto", lga:"Sabon birni"},
     {state:"Sokoto", lga:"Shagari"},
     {state:"Sokoto", lga:"Silame"},
     {state:"Sokoto", lga:"Sokoto North"},
     {state:"Sokoto", lga:"Sokoto South"},
     {state:"Sokoto", lga:"Tambuwal"},
     {state:"Sokoto", lga:"Tqngaza"},
     {state:"Sokoto", lga:"Tureta"},
     {state:"Sokoto", lga:"Wamako"},
     {state:"Sokoto", lga:"Wurno"},
     {state:"Sokoto", lga:"Yabo"},
     {state:"Taraba", lga:"Ardo-kola"},
     {state:"Taraba", lga:"Bali"},
     {state:"Taraba", lga:"Donga"},
     {state:"Taraba", lga:"Gashaka"},
     {state:"Taraba", lga:"Cassol"},
     {state:"Taraba", lga:"Ibi"},
     {state:"Taraba", lga:"Jalingo"},
     {state:"Taraba", lga:"Karin-Lamido"},
     {state:"Taraba", lga:"Kurmi"},
     {state:"Taraba", lga:"Lau"},
     {state:"Taraba", lga:"Sardauna"},
     {state:"Taraba", lga:"Takum"},
     {state:"Taraba", lga:"Ussa"},
     {state:"Taraba", lga:"Wukari"},
     {state:"Taraba", lga:"Yorro"},
     {state:"Taraba", lga:"Zing"},
     {state:"Yobe", lga:"Bade"},
     {state:"Yobe", lga:"Bursari"},
     {state:"Yobe", lga:"Damaturu"},
     {state:"Yobe", lga:"Fika"},
     {state:"Yobe", lga:"Fune"},
     {state:"Yobe", lga:"Geidam"},
     {state:"Yobe", lga:"Gujba"},
     {state:"Yobe", lga:"Gulani"},
     {state:"Yobe", lga:"Jakusko"},
     {state:"Yobe", lga:"Karasuwa"},
     {state:"Yobe", lga:"Karawa"},
     {state:"Yobe", lga:"Machina"},
     {state:"Yobe", lga:"Nangere"},
     {state:"Yobe", lga:"Nguru Potiskum"},
     {state:"Yobe", lga:"Tarmua"},
     {state:"Yobe", lga:"Yunusari"},
     {state:"Yobe", lga:"Yusufari"},
     {state:"Zamfara", lga:"Anka"},
     {state:"Zamfara", lga:"Bakura"},
     {state:"Zamfara", lga:"Birnin Magaji"},
     {state:"Zamfara", lga:"Bukkuyum"},
     {state:"Zamfara", lga:"Bungudu"},
     {state:"Zamfara", lga:"Gummi"},
     {state:"Zamfara", lga:"Gusau"},
     {state:"Zamfara", lga:"Kaura"},
     {state:"Zamfara", lga:"Namoda"},
     {state:"Zamfara", lga:"Maradun"},
     {state:"Zamfara", lga:"Maru"},
     {state:"Zamfara", lga:"Shinkafi"},
     {state:"Zamfara", lga:"Talata Mafara"},
     {state:"Zamfara", lga:"Tsafe"},
     {state:"Zamfara", lga:"Zurmi"}
    ]
