import { checkBox } from "./utilsBtn";


export const heading = [
  {
    serialNumber: "S/N",
    firstName: "First Name",
    lastName: "Last Name",
    roles: "Roles",
    nin: "National Identity Number",
    email: "Email",
    annualSalary: "Annual Gross Salary",
    month: "Monthly Gross Salary",
    relives: "Relieves",
    empty: "",
  },
];


export const Data = [
  {
    id: 1,
    firstName: "EMMANUEL",
    lastName: "DANIYAN",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 10000,
    select: false,
  },
  {
    id: 2,

    firstName: "EMMANUEL",
    lastName: "DANIYAN",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 3,

    firstName: "EMMANUEL",
    lastName: "DANIYAN",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 4,

    firstName: "EMMANUEL",
    lastName: "DANIYAN",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 5,

    firstName: "EMMANUEL",
    lastName: "DANIYAN",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 6,

    firstName: "EMMANUEL",
    lastName: "DANIYAN",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 7,
    lastName: "DANIYAN",
    firstName: "EMMANUEL",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 8,
    lastName: "DANIYAN",
    firstName: "EMMANUEL",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 9,
    lastName: "PROSPER",
    firstName: "PMAN",
    role: "WEB DEVELOPER",
    nin: 987654,
    email: "prosperpman@gmail.com",
    annual: "50000",
    month: "20000",
    relieves: 40000,
    select: false,
  },
  {
    id: 10,
    lastName: "DANIYAN",
    firstName: "EMMANUEL",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 11,
    lastName: "DANIYAN",
    firstName: "EMMANUEL",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
  {
    id: 12,
    lastName: "DANIYAN",
    firstName: "EMMANUEL",
    role: "CEO",
    nin: 1234567,
    email: "spacepen@gmail.com",
    annual: 20000,
    month: 10000,
    relieves: 40000,
    select: false,
  },
];
