name: Update server code

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build React on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        envs: PROJECT_PATH,REPO_URL,SUDO_PASSWORD
        script: |
          cd $PROJECT_PATH
          git pull $REPO_URL
          yarn install
          yarn run build
          echo "$SUDO_PASSWORD" | sudo -S systemctl restart apache2
      env:
        SUDO_PASSWORD: ${{ secrets.PASSWORD }}
        GITHUB_TOKEN: ${{ github.token }}
        PROJECT_PATH: projectabc
        REPO_URL: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}

