name: Deploy to Production

on:
  push:
    branches: master

permissions:
  contents: write

jobs:
  build:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Master Branch to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          envs: PROJECT_PATH,REPO_URL,SUDO_PASSWORD
          script: |
            cd $PROJECT_PATH
            git pull $REPO_URL
        env:
          SUDO_PASSWORD: ${{ secrets.PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}
          PROJECT_PATH: projectabc
          REPO_URL: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }} master
